### ISSUE TITLE
wtf is this 

### ISSUE THREAD

**Issue by kylewr** [TanMan360/Python-Calculator#1]
bro what??

**Comment by TanMan360** [comment]
This is my calculator I made in python. Its basic, so it doesn't have advanced features but I plan on adding more features in an updated calculator later

**Comment by thedhruvhegde** [comment]
> bro what??

Nah he uploaded from a compiler so it's super scuffed. His actual code is at like line 1150 or smth

**Comment by kylewr** [comment]
dee dee vee hedge
